name: hacker_news_app
description: "Hacker News App in Flutter"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.0
  loader_overlay: ^4.0.0
  flutter_spinkit: ^5.2.0
  lottie: ^3.1.1
  animated_text_kit: ^4.2.2
  shimmer: ^3.0.0
  webview_flutter: ^4.7.0
  flutter_widget_from_html: ^0.15.0
  fluttertoast: ^8.2.5
  tutorial_coach_mark: ^1.2.11
  flutter_native_splash: ^2.3.4

flutter_native_splash:
  android: true
  ios: true
  fullscreen: true
  web: false
  image: "assets/icons/png/app_logo.png"
  color: "#2F2E2E"
  color_dark: "#2F2E2E"
  image_dark: "assets/icons/png/app_logo.png"

  android_12:
    image: "assets/icons/png/app_logo_android12.png"
    icon_background_color: "#2F2E2E"
    image_dark: "assets/icons/png/app_logo_android12.png"
    icon_background_color_dark: "#2F2E2E"
    color: "#2F2E2E"
    color_dark: "#2F2E2E"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/icons/svg/
    - assets/icons/jpg/
    - assets/icons/png/
    - .env.development
    - .env.production

  fonts:
    - family: MulishRegular
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
