name: hacker_news_app
description: "Hacker News App in Flutter"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.0
  loader_overlay: ^4.0.0
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: FontMain
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
